package org.awi.fitness

object AppConfig {
    // The Gemini key comes from local.properties (gitignored) via the generated
    // GEMINI_API_KEY constant — the single source for every client Gemini call.
    // No Firestore fetch, no baked-in literal. GEMINI_API_KEY is in this same
    // package (org.awi.fitness), generated by the `generateAppSecrets` Gradle task.
    var geminiApiKey: String = GEMINI_API_KEY
        private set

    fun setGeminiApiKey(key: String) {
        if (key.isNotBlank()) {
            println("[AppConfig] setGeminiApiKey: updating key to ${key.take(10)}...")
            geminiApiKey = key
        }
    }
}
